### ISSUE TITLE
Repository purpose

### ISSUE THREAD

**Issue by dcousens** [fanatid/bitcoinjs-hash#1]
Just curious what the purpose of this repository is for `bitcoinjs`?

It seems you have made a few performance improvements to some of the hash functions,  why not contribute them back to upstream?

**Comment by fanatid** [comment]
@dcousens AFAIR, I just extract code for hashing from `sha.js`/`ripemd160`
functions in this repository is sometimes faster only because they hash only 1 buffer
it was experiment project (see https://github.com/cryptocoinjs/secp256k1-node/pull/86)
and I still not sure about purpose of this repo in `bitcoinjs`

**Comment by dcousens** [comment]
Still in use / worth keeping / worth integrating somewhere else?

**Comment by fanatid** [comment]
`secp256k1-node` doesn't use this package/code
If you want move this package from `bitcoinjs` org, I'm ready move it to my account.

**Comment by dcousens** [comment]
@fanatid if you're OK with that?
Was just checking tests on travis and didn't know what this repository was.
I wouldn't want you to feel like you can't add other repos whenever though.

**Comment by fanatid** [comment]
@dcousens I'm ok with this, just create transfer request because I haven't enough rights for this.
